version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  target-branch: canary
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.27
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: twitch
    versions:
    - 4.4.10
    - 4.4.11
    - 4.4.12
    - 4.4.13
    - 4.4.6
    - 4.4.7
    - 4.4.8
    - 4.4.9
    - 4.5.0
    - 4.5.1
    - 4.5.2
    - 4.5.3
    - 4.5.4
  - dependency-name: twitch-auth
    versions:
    - 4.4.10
    - 4.4.11
    - 4.4.12
    - 4.4.13
    - 4.4.6
    - 4.4.7
    - 4.4.8
    - 4.4.9
    - 4.5.0
    - 4.5.1
    - 4.5.2
    - 4.5.3
    - 4.5.4
  - dependency-name: discord.js
    versions:
    - 12.5.1
    - 12.5.2
  - dependency-name: mongodb
    versions:
    - 3.6.3
    - 3.6.4
    - 3.6.5
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
